apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devboard-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/waddenn/projet-etude/backend, frontend=ghcr.io/waddenn/projet-etude/frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-commit-message: "chore(image-updater): bump images [skip ci]"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devboard
  source:
    repoURL: https://github.com/Waddenn/projet-etude.git
    targetRevision: main
    path: helm/devboard
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
