apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devboard
  
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.5.1
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        
        grafana:
          adminPassword: __GRAFANA_ADMIN_PASSWORD__
          persistence:
            enabled: true
            size: 5Gi
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.devboard.local
            path: /
        
        alertmanager:
          enabled: true
          alertmanagerSpec:
            retention: 120h
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
