apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devboard
  source:
    repoURL: https://github.com/Waddenn/projet-etude.git
    targetRevision: main
    path: argocd/applications
    directory:
      recurse: false
      include: "{root.yaml,devboard-app.yaml,ingress-services.yaml,loki-stack.yaml,monitoring-stack.yaml,vault.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      name: root-app
      jsonPointers:
        - /metadata/finalizers
