apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devboard
  
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.1
    chart: vault
    helm:
      values: |
        server:
          dev:
            enabled: true
            devRootToken: "root"
          
          ingress:
            enabled: false
          
          dataStorage:
            enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: security

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
